### PR TITLE
[DRUP-523]: Refine TnC error handling.

### PR DESCRIPTION
**Pull request by minnur**

### CODE REVIEW

**Review by cnovak — APPROVED** [review]
LGTM

**Comment by Jaesin** [comment]
See: https://github.com/apigee/apigee-m10n-drupal/pull/24#issuecomment-452014982

**Comment by Jaesin** [comment]
Yeah, this is fine, just needs to be rebased against `8.x-1.x`.

**Comment by minnur** [comment]
Lets close this PR in favor of https://github.com/apigee/apigee-m10n-drupal/pull/24

**Pull request closed without merging**
