### PR TITLE
[#253] Set the target_type for ratePlan base field

### LINKED ISSUE #253: Unable to Purchase a  Rate Plan
## Description
When I tried to Purchase a Rate Plan as Developer Drupal is Throwing Error.
The issue happens due to a lack of Terms and Conditions defined for the Apigee Organisation.
this behavior should be handled 
```
Url: http://{host}/user/31/monetization/product-bundle/calculator_pkg-myax/plan/calculator_pkg-myax_calculator_prepaid/purchase
The website encountered an unexpected error. Please try again later.

Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "calculator_pkg-myax_calculator_prepaid" LINE 5: ...d_data.status = '1') AND (node_field_data.nid IN ('calculato... ^: SELECT base_table.vid AS vid, base_table.nid AS nid FROM {node} base_table INNER JOIN {node_field_data} node_field_data ON node_field_data.nid = base_table.nid WHERE (node_field_data.status = :db_condition_placeholder_0) AND (node_field_data.nid IN (:db_condition_placeholder_1)); Array ( [:db_condition_placeholder_0] => 1 [:db_condition_placeholder_1] => calculator_pkg-myax_calculator_prepaid ) in Drupal\Core\Entity\Plugin\EntityReferenceSelection\DefaultSelection->validateReferenceableEntities() (line 387 of core/lib/Drupal/Core/Entity/Plugin/EntityReferenceSelection/DefaultSelection.php).
Drupal\Core\Database\Statement->execute() (Line: 640)
Drupal\Core\Database\Connection->query() (Line: 202)
Drupal\Core\Database\Driver\pgsql\Connection->query() (Line: 510)
Drupal\Core\Database\Query\Select->execute() (Line: 145)
Drupal\Core\Database\Driver\pgsql\Select->execute() (Line: 267)
Drupal\Core\Entity\Query\Sql\Query->result() (Line: 83)
Drupal\Core\Entity\Query\Sql\Query->execute() (Line: 387)
Drupal\Core\Entity\Plugin\EntityReferenceSelection\DefaultSelection->validateReferenceableEntities() (Line: 133)
Drupal\Core\Entity\Plugin\Validation\Constraint\ValidReferenceConstraintValidator->validate() (Line: 196)
Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateConstraints() (Line: 148)
Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode() (Line: 158)
Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validateNode() (Line: 100)
Drupal\Core\TypedData\Validation\RecursiveContextualValidator->validate() (Line: 90)
Drupal\Core\TypedData\Validation\RecursiveValidator->validate() (Line: 132)
Drupal\Core\TypedData\TypedData->validate() (Line: 364)
Drupal\apigee_edge\Entity\FieldableEdgeEntityBase->validate() (Line: 75)
Drupal\apigee_edge\Entity\Form\FieldableEdgeEntityForm->validateForm() (Line: 41)
Drupal\apigee_m10n\Entity\Form\FieldableMonetizationEntityForm->validateForm()
call_user_func_array() (Line: 82)
Drupal\Core\Form\FormValidator->executeValidateHandlers() (Line: 273)
Drupal\Core\Form\FormValidator->doValidateForm() (Line: 118)
Drupal\Core\Form\FormValidator->validateForm() (Line: 589)
Drupal\Core\Form\FormBuilder->processForm() (Line: 321)
Drupal\Core\Form\FormBuilder->buildForm() (Line: 61)
Drupal\Core\Entity\EntityFormBuilder->getForm() (Line: 86)
Drupal\apigee_m10n\Entity\Controller\PurchaseRatePlanController->purchaseForm()
call_user_func_array() (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 573)
Drupal\Core\Render\Renderer->executeInRenderContext() (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext() (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 151)
Symfony\Component\HttpKernel\HttpKernel->handleRaw() (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle() (Line: 57)
Drupal\Core\StackMiddleware\Session->handle() (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle() (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass() (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle() (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle() (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle() (Line: 23)
Stack\StackedHttpKernel->handle() (Line: 708)
Drupal\Core\DrupalKernel->handle() (Line: 19
```)

## Steps to Reproduce
Steps to reproduce the behavior:
1. I have added the Prepaid Balance enough to cover the plan cost
2. If the organization does not have Terms and Condition is Defined. 
3. went to the rate plan page and tried to purchase a plan in the Drupal 8 portal

## Actual Behavior
It's Throwing Drupal errors

## Expected Behavior
it should enable the rate plan 


## Notes
Maybe an issue with the entity.

## Version Info
apigee/apigee-client-php                 2.0.5        Client library for connecting to the Apigee Edge API.
apigee/apigee_devportal_kickstart        1.20.0       A fast demo and starting point for Apigee Developer Portals.
asm89/stack-cors                         1.3.0        Cross-origin resource sharing library and stack middleware
behat/mink                               v1.8.1       Browser controller/emulator abstraction for PHP
behat/mink-browserkit-driver             v1.3.4       Symfony2 BrowserKit driver for Mink framework
behat/mink-goutte-driver                 v1.2.1       Goutte driver for Mink framework
behat/mink-selenium2-driver              v1.4.0       Selenium2 (WebDriver) driver for Mink framework
chi-teck/drupal-code-generator           1.32.1       Drupal code generator
clue/stream-filter                       v1.4.1       A simple and modern approach to stream filtering in PHP
commerceguys/addressing                  v1.0.9       Addressing library powered by CLDR and Google's address data.
commerceguys/intl                        v1.0.6       Internationalization library powered by CLDR data.
composer/ca-bundle                       1.2.8        Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bu...
composer/composer                        1.10.13      Composer helps you declare, manage and install dependencies of PHP projects. It ensures yo...
composer/installers                      v1.9.0       A multi-framework Composer library installer
composer/semver                          1.5.1        Semver library that offers utilities, version constraint parsing and validation.
composer/spdx-licenses                   1.5.4        SPDX licenses list and validation library.
composer/xdebug-handler                  1.4.3        Restarts a process without Xdebug.
consolidation/annotated-command          2.12.0       Initialize Symfony Console commands from annotated command class methods.
consolidation/config                     1.2.1        Provide configuration services for a commandline tool.
consolidation/filter-via-dot-access-data 1.0.0        This project uses dflydev/dot-access-data to provide simple output filtering for applicati...
consolidation/log                        1.1.1        Improved Psr-3 / Psr\Log logger based on Symfony Console components.
consolidation/output-formatters          3.5.0        Format text by applying transformations provided by plug-in formatters.
consolidation/robo                       1.4.12       Modern task runner
consolidation/self-update                1.2.0        Provides a self:update command for Symfony Console applications.
consolidation/site-alias                 3.0.1        Manage alias records for local and remote sites.
consolidation/site-process               2.1.0        A thin wrapper around the Symfony Process Component that allows applications to use the Si...
container-interop/container-interop      1.2.0        Promoting the interoperability of container objects (DIC, SL, etc.)
cweagans/composer-patches                1.6.7        Provides a way to patch Composer packages.
dflydev/dot-access-data                  v1.1.0       Given a deep data structure, access data by dot notation.
dnoegel/php-xdg-base-dir                 v0.1.1       implementation of xdg base directory specification for php
doctrine/annotations                     v1.4.0       Docblock Annotations Parser
doctrine/cache                           v1.6.2       Caching library offering an object-oriented API for many cache backends
doctrine/collections                     v1.4.0       Collections Abstraction library
doctrine/common                          v2.7.3       Common Library for Doctrine projects
doctrine/inflector                       v1.2.0       Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                    1.3.1        A small, lightweight utility to instantiate objects in PHP without invoking their construc...
doctrine/lexer                           1.0.2        PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
drupal/address                           1.8.0        Provides functionality for storing, validating and displaying international postal addresses.
drupal/admin_toolbar                     2.3.0        Provides a drop-down menu interface to the core Drupal Toolbar.
drupal/adminimal_admin_toolbar           1.11.0       Adminimal styling brought to admin toolbar.
drupal/apigee_api_catalog                2.4.0        Apigee API Catalog for Drupal
drupal/apigee_edge                       1.16.0       Apigee Edge for Drupal.
drupal/apigee_m10n                       1.6.0        Apigee Edge Monetization for Drupal
drupal/better_exposed_filters            5.0.0-beta1  Replaces the Views default single- or multi-select boxes with more advanced options.
drupal/coder                             8.3.10       Coder is a library to review Drupal code.
drupal/commerce                          2.21.0       Drupal Commerce is a flexible eCommerce solution.
drupal/components                        2.0.0-beta3  Sets up folders of components defined by your theme or module
drupal/core                              8.9.6        Drupal is an open source content management platform powering millions of websites and app...
drupal/core-composer-scaffold            8.9.6        A flexible Composer project scaffold builder.
drupal/core-dev                          8.9.6        require-dev dependencies from drupal/drupal; use in addition to drupal/core-recommended to...
drupal/core-project-message              8.9.6        Adds a message after Composer installation.
drupal/core-recommended                  8.9.6        Locked core dependencies; require this project INSTEAD OF drupal/core.
drupal/ctools                            3.4.0        Provides a number of utility and helper APIs for Drupal developers and site builders.
drupal/default_content                   1.0.0-alpha9 Imports default content when a module is enabled
drupal/email_registration                1.1.0        Allows users to register with an email address as their username.
drupal/entity                            1.1.0        Provides expanded entity APIs, which will be moved to Drupal core one day.
drupal/entity_reference_revisions        1.8.0        Entity Reference Revisions
drupal/file_link                         2.0.0        Extends the core Link module by storing metadata about the target file.
drupal/fontawesome                       2.17.0       The web's most popular icon set and toolkit.
drupal/inline_entity_form                1.0.0-rc7    Provides a widget for inline management (creation, modification, removal) of referenced en...
drupal/jquery_ui                         1.4.0        Provides jQuery UI library.
drupal/jquery_ui_datepicker              1.0.0        Provides jQuery UI Datepicker library.
drupal/jquery_ui_slider                  1.1.0        Provides jQuery UI Slider library.
drupal/jquery_ui_touch_punch             1.0.0        Provides jQuery UI Touch Punch library.
drupal/key                               1.14.0       Provides the ability to manage site-wide keys
drupal/openid_connect                    1.0.0-rc1    A pluggable client implementation for the OpenID Connect protocol.
drupal/paragraphs                        1.12.0       Enables the creation of Paragraphs entities.
drupal/pathauto                          1.8.0        Provides a mechanism for modules to automatically generate aliases for the content they ma...
drupal/profile                           1.1.0        Provides configurable user profiles.
drupal/radix                             4.10.0       Radix is a base theme for Drupal. It has Bootstrap, Sass, BrowserSync and Font Awesome bui...
drupal/requirement                       1.1.0        A Drupal module to that gives modules a way to declare configuration requirement and sugge...
drupal/smtp                              1.0.0        Allow for site emails to be sent through an SMTP server of your choice.
drupal/state_machine                     1.0.0        Provides code-driven workflow functionality.
drupal/token                             1.7.0        Provides a user interface for the Token API, some missing core tokens.
drush/drush                              9.7.2        Drush is a command line shell and scripting interface for Drupal, a veritable Swiss Army k...
easyrdf/easyrdf                          0.9.1        EasyRdf is a PHP library designed to make it easy to consume and produce RDF.
egulias/email-validator                  2.1.17       A library for validating emails against several RFCs
fabpot/goutte                            v3.2.3       A simple PHP Web Scraper
fightbulc/moment                         1.32.1       Parse, validate, manipulate, and display dates in PHP w/ i18n support. Inspired by moment.js
firebase/php-jwt                         v5.2.0       A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the ...
grasmash/expander                        1.0.0        Expands internal property references in PHP arrays file.
grasmash/yaml-expander                   1.4.0        Expands internal property references in a yaml file.
guzzlehttp/guzzle                        6.5.4        Guzzle is a PHP HTTP client library
guzzlehttp/promises                      v1.3.1       Guzzle promises library
guzzlehttp/psr7                          1.6.1        PSR-7 message implementation that also provides common utility methods
instaclick/php-webdriver                 1.4.7        PHP WebDriver for Selenium 2
jcalderonzumba/gastonjs                  v1.2.0       PhantomJS API based server for webpage automation
jcalderonzumba/mink-phantomjs-driver     v0.3.3       PhantomJS driver for Mink framework
justinrainbow/json-schema                5.2.10       A library to validate a json schema.
laminas/laminas-diactoros                1.8.7p2      PSR HTTP Message implementations
laminas/laminas-escaper                  2.6.1        Securely and safely escape HTML, HTML attributes, JavaScript, CSS, and URLs
laminas/laminas-feed                     2.12.2       provides functionality for consuming RSS and Atom feeds
laminas/laminas-stdlib                   3.2.1        SPL extensions, array utilities, error handlers, and more
laminas/laminas-zendframework-bridge     1.0.4        Alias legacy ZF class names to Laminas Project equivalents.
league/container                         2.4.1        A fast and intuitive dependency injection container.
league/period                            3.4.0        A time range immutable value object
masterminds/html5                        2.3.0        An HTML5 parser and serializer.
mikey179/vfsstream                       v1.6.8       Virtual file system to mock the real file system in unit tests.
myclabs/deep-copy                        1.10.1       Create deep copies (clones) of your objects
nikic/php-parser                         v4.10.2      A PHP parser written in PHP
paragonie/random_compat                  v9.99.99     PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
pear/archive_tar                         1.4.9        Tar file management class with compression support (gzip, bzip2, lzma2)
pear/console_getopt                      v1.4.3       More info available on: http://pear.php.net/package/Console_Getopt
pear/pear-core-minimal                   v1.10.10     Minimal set of PEAR core files to be used as composer dependency
pear/pear_exception                      v1.0.1       The PEAR Exception base class.
phar-io/manifest                         1.0.3        Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                          2.0.1        Library for handling version information and constraints
php-http/client-common                   1.10.0       Common HTTP Client implementations and tools for HTTPlug
php-http/discovery                       1.12.0       Finds installed HTTPlug implementations and PSR-7 message factories
php-http/guzzle6-adapter                 v1.1.1       Guzzle 6 HTTP Adapter
php-http/httplug                         v1.1.0       HTTPlug, the HTTP client abstraction for PHP
php-http/message                         1.9.0        HTTP Message related tools
php-http/message-factory                 v1.0.2       Factory interfaces for PSR-7 HTTP Message
php-http/promise                         1.1.0        Promise used for asynchronous HTTP requests
phpdocumentor/reflection-common          2.2.0        Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock        4.3.4        With this component, a library can provide support for annotations via DocBlocks or otherw...
phpdocumentor/type-resolver              1.4.0        A PSR-5 based resolver of Class names, Types and Structural Element Names
phpmailer/phpmailer                      v6.1.8       PHPMailer is a full-featured email creation and transfer class for PHP
phpspec/prophecy                         v1.10.3      Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage                6.1.4        Library that provides collection, processing, and rendering functionality for PHP code cov...
phpunit/php-file-iterator                2.0.2        FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template                1.2.1        Simple template engine.
phpunit/php-timer                        2.1.2        Utility class for timing
phpunit/php-token-stream                 3.1.1        Wrapper around PHP's tokenizer extension.
phpunit/phpunit                          7.5.20       The PHP Unit Testing framework.
psr/container                            1.0.0        Common Container Interface (PHP FIG PSR-11)
psr/http-message                         1.0.1        Common interface for HTTP messages
psr/log                                  1.1.3        Common interface for logging libraries
psy/psysh                                v0.10.4      An interactive shell for modern PHP.
ralouphie/getallheaders                  3.0.3        A polyfill for getallheaders.
sebastian/code-unit-reverse-lookup       1.0.1        Looks up which function or method a line of code belongs to
sebastian/comparator                     3.0.2        Provides the functionality to compare PHP values for equality
sebastian/diff                           3.0.2        Diff implementation
sebastian/environment                    4.2.3        Provides functionality to handle HHVM/PHP environments
sebastian/exporter                       3.1.2        Provides the functionality to export PHP variables for visualization
sebastian/global-state                   2.0.0        Snapshotting of global state
sebastian/object-enumerator              3.0.3        Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector               1.1.1        Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context              3.0.0        Provides functionality to recursively process PHP variables
sebastian/resource-operations            2.0.1        Provides a list of PHP built-in functions that operate on resources
sebastian/version                        2.0.1        Library that helps with managing the version number of Git-hosted PHP projects
seld/jsonlint                            1.8.2        JSON Linter
seld/phar-utils                          1.1.1        PHAR file format utilities, for when PHP phars you up
sirbrillig/phpcs-variable-analysis       v2.8.3       A PHPCS sniff to detect problems with variables.
squizlabs/php_codesniffer                3.5.6        PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a define...
stack/builder                            v1.0.5       Builder for stack middlewares based on HttpKernelInterface.
symfony-cmf/routing                      1.4.1        Extends the Symfony2 routing component for dynamic routes and chaining several routers
symfony/browser-kit                      v3.4.45      Symfony BrowserKit Component
symfony/class-loader                     v3.4.41      Symfony ClassLoader Component
symfony/console                          v3.4.41      Symfony Console Component
symfony/css-selector                     v3.4.45      Symfony CssSelector Component
symfony/debug                            v3.4.41      Symfony Debug Component
symfony/dependency-injection             v3.4.41      Symfony DependencyInjection Component
symfony/deprecation-contracts            v2.2.0       A generic function and convention to trigger deprecation notices
symfony/dom-crawler                      v3.4.45      Symfony DomCrawler Component
symfony/event-dispatcher                 v3.4.41      Symfony EventDispatcher Component
symfony/filesystem                       v3.4.45      Symfony Filesystem Component
symfony/finder                           v3.4.45      Symfony Finder Component
symfony/http-foundation                  v3.4.41      Symfony HttpFoundation Component
symfony/http-kernel                      v3.4.44      Symfony HttpKernel Component
symfony/inflector                        v5.1.6       Symfony Inflector Component
symfony/lock                             v3.4.45      Symfony Lock Component
symfony/options-resolver                 v4.4.14      Symfony OptionsResolver Component
symfony/phpunit-bridge                   v3.4.45      Symfony PHPUnit Bridge
symfony/polyfill-ctype                   v1.17.0      Symfony polyfill for ctype functions
symfony/polyfill-iconv                   v1.17.0      Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme           v1.18.1      Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn                v1.17.0      Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer         v1.18.1      Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring                v1.17.0      Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                   v1.17.0      Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70                   v1.17.0      Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72                   v1.17.0      Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php80                   v1.18.1      Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-util                    v1.17.0      Symfony utilities for portability of PHP codes
symfony/process                          v3.4.41      Symfony Process Component
symfony/property-access                  v4.4.14      Symfony PropertyAccess Component
symfony/property-info                    v4.4.14      Symfony Property Info Component
symfony/psr-http-message-bridge          v1.1.2       PSR HTTP message bridge
symfony/routing                          v3.4.41      Symfony Routing Component
symfony/serializer                       v3.4.41      Symfony Serializer Component
symfony/string                           v5.1.6       Symfony String component
symfony/translation                      v3.4.41      Symfony Translation Component
symfony/validator                        v3.4.41      Symfony Validator Component
symfony/var-dumper                       v4.4.14      Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                             v3.4.41      Symfony Yaml Component
theseer/tokenizer                        1.2.0        A small library for converting tokenized PHP source code into XML and potentially other fo...
twig/twig                                v1.42.5      Twig, the flexible, fast, and secure template language for PHP
typo3/phar-stream-wrapper                v3.1.4       Interceptors for PHP's native phar:// stream handling
webflo/drupal-finder                     1.2.0        Helper class to locate a Drupal installation from a given path.
webmozart/assert                         1.9.1        Assertions to validate method input/output with nice error messages.
webmozart/path-util                      2.3.0        A robust cross-platform utility for normalizing, comparing and modifying file paths.

### PR DESCRIPTION
**Pull request by shadcn**
Fixed #253

### CODE REVIEW

**Comment by arlina-espinoza** [comment]
@arshad Tests are failing because CI is running D9 tests against a dev version, I'll fix in a separate PR and ping you for review.

**Comment by shadcn** [comment]
@arlina-espinoza Thank you.

**Comment by arlina-espinoza** [comment]
> @arshad Tests are failing because CI is running D9 tests against a dev version, I'll fix in a separate PR and ping you for review.

Pushed PR for review #255 .  Your tests should pass after you merge that in :)

**Review by arlina-espinoza — APPROVED** [review]
This was a difficult one to catch! Thanks @arshad :partying_face:

**Pull request merged**
