### PR TITLE
[#212] Load the billing type from the mint developer

### LINKED ISSUE #212: Billing Type not displayed for newly registered users
**Describe the bug**
The billing type is not displayed for newly registered users in system, displayed in red:

billing-type missing

**To Reproduce**
1. Register on a developer portal that is connected to a monetized org
2. Click on **My account**
3. Click on **Balance and plans**
4. Click on **Billing details**
4. View that `Billing Type` is not set to any value.

**Expected behavior**
A developer should be set to "PREPAID" or "POSTPAID" when created

**Screenshots**

**Version Info**
`drupal/apigee_m10n                       1.2.0        Apigee Edge Monetization for Drupal`

### PR DESCRIPTION
**Pull request by shadcn**
Fixes #212

### CODE REVIEW

**Review by arlina-espinoza — CHANGES_REQUESTED** [review]
This looks good, but we also need to use the monetized developer object in `\Drupal\apigee_m10n\Monetization::isDeveloperPrepaid()`, from:
```
$developer = Developer::load($account->getEmail());
$billing_type = $developer->getAttributeValue(static::BILLING_TYPE_ATTR);
```
to:
```
$developer = $this->sdk_controller_factory->developerController()->load($account->getEmail());
$billing_type = $developer->getBillingType();
```
And check that tests are passing with this change.

**Comment by shadcn** [comment]
@arlina-espinoza I made the change. We should probably switch team as well?

https://github.com/apigee/apigee-m10n-drupal/blob/e5c2b5383b452f470ca25cd215ee7f5e92c9dfa7/modules/apigee_m10n_teams/src/Form/BillingDetailsForm.php#L119-L132

**Review by arlina-espinoza — APPROVED** [review]
There were a lot of changes to the tests, but thanks @arshad for getting it done! 
PR LGTM :+1:

**Comment by arlina-espinoza** [comment]
> @arlina-espinoza I made the change. We should probably switch team as well?
> 
> https://github.com/apigee/apigee-m10n-drupal/blob/e5c2b5383b452f470ca25cd215ee7f5e92c9dfa7/modules/apigee_m10n_teams/src/Form/BillingDetailsForm.php#L119-L132

@arshad I've created a follow up ticket for that: https://github.com/apigee/apigee-m10n-drupal/issues/224

**Pull request merged**
